%import common.CNAME -> NAME
%import common.WS
%ignore WS

PLUS: "+"
MINUS: "-"
AT: "@"
AS: /as/i
IF: /if/i
ELSE: /else/i

start: expr
expr: conditional
conditional: additive IF additive ELSE conditional   -> ifexpr
          | additive
additive: at_expr op*
op: PLUS cast_expr     -> plus
  | MINUS cast_expr    -> minus
?at_expr: cast_expr AT cast_expr   -> resolve_ts
        | cast_expr
cast_expr: NAME AS NAME   -> cast
         | NAME           -> name
